/**
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveSecurityApiClient);
  }
}(this, function(expect, CloudmersiveSecurityApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StringXssProtectionResult', function() {
    it('should create an instance of StringXssProtectionResult', function() {
      // uncomment below and update the code to test StringXssProtectionResult
      //var instane = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
      //expect(instance).to.be.a(CloudmersiveSecurityApiClient.StringXssProtectionResult);
    });

    it('should have the property successful (base name: "Successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instane = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
      //expect(instance).to.be();
    });

    it('should have the property containedXss (base name: "ContainedXss")', function() {
      // uncomment below and update the code to test the property containedXss
      //var instane = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
      //expect(instance).to.be();
    });

    it('should have the property originalInput (base name: "OriginalInput")', function() {
      // uncomment below and update the code to test the property originalInput
      //var instane = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
      //expect(instance).to.be();
    });

    it('should have the property normalizedResult (base name: "NormalizedResult")', function() {
      // uncomment below and update the code to test the property normalizedResult
      //var instane = new CloudmersiveSecurityApiClient.StringXssProtectionResult();
      //expect(instance).to.be();
    });

  });

}));
