/**
 * securityapi
 * The security APIs help you detect and block security threats.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveSecurityApiClient);
  }
}(this, function(expect, CloudmersiveSecurityApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveSecurityApiClient.ContentThreatDetectionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContentThreatDetectionApi', function() {
    describe('contentThreatDetectionAutomaticThreatDetectionString', function() {
      it('should call contentThreatDetectionAutomaticThreatDetectionString successfully', function(done) {
        //uncomment below and update the code to test contentThreatDetectionAutomaticThreatDetectionString
        //instance.contentThreatDetectionAutomaticThreatDetectionString(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentThreatDetectionCheckSqlInjectionString', function() {
      it('should call contentThreatDetectionCheckSqlInjectionString successfully', function(done) {
        //uncomment below and update the code to test contentThreatDetectionCheckSqlInjectionString
        //instance.contentThreatDetectionCheckSqlInjectionString(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentThreatDetectionCheckXxe', function() {
      it('should call contentThreatDetectionCheckXxe successfully', function(done) {
        //uncomment below and update the code to test contentThreatDetectionCheckXxe
        //instance.contentThreatDetectionCheckXxe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentThreatDetectionDetectInsecureDeserializationJsonString', function() {
      it('should call contentThreatDetectionDetectInsecureDeserializationJsonString successfully', function(done) {
        //uncomment below and update the code to test contentThreatDetectionDetectInsecureDeserializationJsonString
        //instance.contentThreatDetectionDetectInsecureDeserializationJsonString(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('contentThreatDetectionProtectXss', function() {
      it('should call contentThreatDetectionProtectXss successfully', function(done) {
        //uncomment below and update the code to test contentThreatDetectionProtectXss
        //instance.contentThreatDetectionProtectXss(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
